// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLtETGGO0oGS1xRvxk9qDvnjDoUYBCgY',
    appId: '1:806978191913:web:425d92e90f655e88ca5238',
    messagingSenderId: '806978191913',
    projectId: 'roomy-1c1cf',
    authDomain: 'roomy-1c1cf.firebaseapp.com',
    storageBucket: 'roomy-1c1cf.firebasestorage.app',
    measurementId: 'G-JS4E7F49D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF-oisMl5qvbMtZm2EZfs9zTBUJGHzxMw',
    appId: '1:806978191913:android:df0b3f526f9d5a23ca5238',
    messagingSenderId: '806978191913',
    projectId: 'roomy-1c1cf',
    storageBucket: 'roomy-1c1cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zHGTO-22VilHjbwkwkuT9igUWb-kN6Y',
    appId: '1:806978191913:ios:f958763403df8683ca5238',
    messagingSenderId: '806978191913',
    projectId: 'roomy-1c1cf',
    storageBucket: 'roomy-1c1cf.firebasestorage.app',
    iosBundleId: 'com.skimgworld.romy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_zHGTO-22VilHjbwkwkuT9igUWb-kN6Y',
    appId: '1:806978191913:ios:f958763403df8683ca5238',
    messagingSenderId: '806978191913',
    projectId: 'roomy-1c1cf',
    storageBucket: 'roomy-1c1cf.firebasestorage.app',
    iosBundleId: 'com.skimgworld.romy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYLtETGGO0oGS1xRvxk9qDvnjDoUYBCgY',
    appId: '1:806978191913:web:42fab953583605adca5238',
    messagingSenderId: '806978191913',
    projectId: 'roomy-1c1cf',
    authDomain: 'roomy-1c1cf.firebaseapp.com',
    storageBucket: 'roomy-1c1cf.firebasestorage.app',
    measurementId: 'G-YMRF1G695B',
  );
}
